useDotenv: true

service: secure-document-vault-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:MY_AWS_REGION}
  environment:
    MY_AWS_BUCKET_NAME: ${env:MY_AWS_BUCKET_NAME}
    MY_AWS_REGION: ${env:MY_AWS_REGION}

functions:
  uploadDocument:
    handler: handlers/uploadDocument.handler
    events:
      - http:
          path: documents/upload
          method: post
          cors: true

plugins:
  - serverless-dotenv-plugin
